export default {
  GET_CARD_LIST: "GET_CARD_LIST",
  GET_CARD_LIST_SUCCESSFUL: "GET_CARD_LIST_SUCCESSFUL",
  GET_CARD_LIST_FAILURE: "GET_CARD_LIST_FAILURE",
  SEARCH_RECORD_REQUEST: "SEARCH_RECORD_REQUEST",
  SEARCH_RECORD_SUCCESSFUL: "SEARCH_RECORD_SUCCESSFUL",
  LIMIT: "LIMIT",
};
